#
# Edrak Analytics - Optimized Docker Compose Configuration
# Lightweight setup for production deployment
#

services:
  db:
    env_file: docker/.env.edrak
    image: postgres:15
    container_name: edrak_db
    restart: unless-stopped
    volumes:
      - db_home:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: edrak_analytics
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: Edrak_Superset2025

  redis:
    image: redis:7-alpine
    container_name: edrak_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    container_name: edrak_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/ssl:/etc/ssl/certs:ro
      - ./docker/ssl:/etc/ssl/private:ro
    depends_on:
      - edrak_app

  edrak_app:
    env_file: docker/.env.edrak
    build:
      context: .
      target: lean
      args:
        DEV_MODE: "false"
        BUILD_TRANSLATIONS: "false"
    container_name: edrak_app
    restart: unless-stopped
    expose:
      - "8088"
    depends_on:
      - db
    volumes:
      # Do not mount source code or docker folder in production; it overwrites built assets
      - ./superset_config.py:/app/pythonpath/superset_config.py
      - superset_home:/app/superset_home
    environment:
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]

volumes:
  superset_home:
    external: false
  db_home:
    external: false
  redis_data:
    external: false
